<?php

declare(strict_types=1);

$boolean = static fn (mixed $value, bool $default): bool => filter_var(
    $value,
    FILTER_VALIDATE_BOOLEAN,
    FILTER_NULL_ON_FAILURE
) ?? $default;
$string = static function (mixed $value, string $default): string {
    $value = trim((string) $value);

    return $value !== '' ? $value : $default;
};

$defaultCurseForgeProxyUrl = 'https://blueit42.vercel.app'.'/api'.'/curseforge'.'/proxy';
$defaultCurseForgeProxySecret = 'blueit42-minecraft-toolkit-proxy-v1';

return [
    'enabled' => $boolean(env('MINECRAFT_TOOLKIT_ENABLED', true), true),
    'admins_only' => $boolean(env('MINECRAFT_TOOLKIT_ADMINS_ONLY', false), false),
    'backup_before_overwrite' => $boolean(env('MINECRAFT_TOOLKIT_BACKUP_BEFORE_OVERWRITE', true), true),
    'modrinth_enabled' => $boolean(env('MINECRAFT_TOOLKIT_MODRINTH_ENABLED', true), true),
    'curseforge_enabled' => $boolean(env('MINECRAFT_TOOLKIT_CURSEFORGE_ENABLED', true), true),
    // Default public flow uses the BlueIT service so the real CurseForge API key stays outside the plugin source.
    // Private/self-hosted installs may override the service URL, shared secret, or use a direct local API key in .env.
    'curseforge_proxy_url' => rtrim($string(env('MINECRAFT_TOOLKIT_CURSEFORGE_PROXY_URL', $defaultCurseForgeProxyUrl), $defaultCurseForgeProxyUrl), '/'),
    'curseforge_proxy_secret' => $string(env('MINECRAFT_TOOLKIT_CURSEFORGE_PROXY_SECRET', $defaultCurseForgeProxySecret), $defaultCurseForgeProxySecret),
    'curseforge_proxy_client_id' => env('MINECRAFT_TOOLKIT_CURSEFORGE_PROXY_CLIENT_ID', 'minecraft-toolkit'),
    'curseforge_proxy_signed_requests' => $boolean(env('MINECRAFT_TOOLKIT_CURSEFORGE_PROXY_SIGNED_REQUESTS', true), true),
    // Optional local direct API key override for private/self-hosted installs only.
    'curseforge_api_key' => env('MINECRAFT_TOOLKIT_CURSEFORGE_API_KEY', ''),
    'updater_enabled' => $boolean(env('MINECRAFT_TOOLKIT_UPDATER_ENABLED', true), true),
    'version_change_enabled' => $boolean(env('MINECRAFT_TOOLKIT_VERSION_CHANGE_ENABLED', true), true),
    'version_change_users_enabled' => $boolean(env('MINECRAFT_TOOLKIT_VERSION_CHANGE_USERS_ENABLED', true), true),
    'crossplay_enabled' => $boolean(env('MINECRAFT_TOOLKIT_CROSSPLAY_ENABLED', true), true),
    'bedrock_port_required' => $boolean(env('MINECRAFT_TOOLKIT_BEDROCK_PORT_REQUIRED', true), true),
    'security_audit_log_enabled' => $boolean(env('MINECRAFT_TOOLKIT_SECURITY_AUDIT_LOG_ENABLED', true), true),
    'risk_gate_startup_edits_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_STARTUP_EDITS_ADMIN_ONLY', false), false),
    'risk_gate_version_risk_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_VERSION_RISK_ADMIN_ONLY', false), false),
    'risk_gate_package_removal_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_PACKAGE_REMOVAL_ADMIN_ONLY', false), false),
    'risk_gate_curseforge_usage_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_CURSEFORGE_USAGE_ADMIN_ONLY', false), false),
    'risk_gate_crossplay_setup_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_CROSSPLAY_SETUP_ADMIN_ONLY', false), false),
    'risk_gate_raw_properties_admin_only' => $boolean(env('MINECRAFT_TOOLKIT_RISK_GATE_RAW_PROPERTIES_ADMIN_ONLY', false), false),
    'bedrock_download_url' => env('MINECRAFT_TOOLKIT_BEDROCK_DOWNLOAD_URL', 'https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.26.23.1.zip'),
    'bedrock_download_version' => env('MINECRAFT_TOOLKIT_BEDROCK_DOWNLOAD_VERSION', '1.26.23.1'),
    'http_timeout' => max(5, (int) env('MINECRAFT_TOOLKIT_HTTP_TIMEOUT', 20)),
    'download_timeout' => max(30, (int) env('MINECRAFT_TOOLKIT_DOWNLOAD_TIMEOUT', 300)),
    'setup_backup_timeout_minutes' => max(15, (int) env('MINECRAFT_TOOLKIT_SETUP_BACKUP_TIMEOUT_MINUTES', 120)),
    'compatibility_cache_minutes' => max(0, (int) env('MINECRAFT_TOOLKIT_COMPATIBILITY_CACHE_MINUTES', 30)),
    'scheduled_update_checks' => $boolean(env('MINECRAFT_TOOLKIT_SCHEDULED_UPDATE_CHECKS', true), true),
    'post_update_health_check' => $boolean(env('MINECRAFT_TOOLKIT_POST_UPDATE_HEALTH_CHECK', false), false),
    'post_update_health_wait_seconds' => max(15, min(300, (int) env('MINECRAFT_TOOLKIT_POST_UPDATE_HEALTH_WAIT', 60))),
    'block_private_download_ips' => $boolean(env('MINECRAFT_TOOLKIT_BLOCK_PRIVATE_DOWNLOAD_IPS', true), true),
    'hash_required' => $boolean(env('MINECRAFT_TOOLKIT_HASH_REQUIRED', false), false),
    // Java 25 supports class file version 69. Set to 0 to disable this safety check.
    'java_class_version_max' => (int) env('MINECRAFT_TOOLKIT_JAVA_CLASS_VERSION_MAX', 69),
    'max_icon_bytes' => max(65536, (int) env('MINECRAFT_TOOLKIT_MAX_ICON_BYTES', 2097152)),
    'max_package_bytes' => max(1048576, (int) env('MINECRAFT_TOOLKIT_MAX_PACKAGE_BYTES', 104857600)),
    'max_jar_entries' => max(100, (int) env('MINECRAFT_TOOLKIT_MAX_JAR_ENTRIES', 20000)),
    'max_jar_entry_bytes' => max(1048576, (int) env('MINECRAFT_TOOLKIT_MAX_JAR_ENTRY_BYTES', 52428800)),
    'user_agent' => env('MINECRAFT_TOOLKIT_USER_AGENT', 'BlueIT-MinecraftToolkit/1.3.7'),
    'blueit_announcements_enabled' => $boolean(env('MINECRAFT_TOOLKIT_BLUEIT_ANNOUNCEMENTS_ENABLED', true), true),
    'blueit_announcements_url' => rtrim((string) env('MINECRAFT_TOOLKIT_BLUEIT_ANNOUNCEMENTS_URL', 'https://blueit42.vercel.app/api/announcements'), '/'),
    'blueit_announcements_secret' => env('MINECRAFT_TOOLKIT_BLUEIT_ANNOUNCEMENTS_SECRET', 'blueit42-announcements-v1'),
    'blueit_announcements_poll_seconds' => max(5, (int) env('MINECRAFT_TOOLKIT_BLUEIT_ANNOUNCEMENTS_POLL_SECONDS', 10)),
    'bedrock_fallback_versions' => array_values(array_filter(array_map('trim', explode(',', (string) env('MINECRAFT_TOOLKIT_BEDROCK_FALLBACK_VERSIONS', 'latest,1.26.23.1'))))),
    'setup_templates' => [
        'vanilla_survival' => [
            'label' => 'Vanilla Survival',
            'description' => 'Simple survival defaults for small public or private Java servers.',
            'software' => 'vanilla',
            'motd' => 'A Vanilla Survival Server',
            'max_players' => 20,
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'online_mode' => true,
            'whitelist' => false,
            'pvp' => true,
            'allow_nether' => true,
            'spawn_protection' => 16,
            'view_distance' => 10,
            'simulation_distance' => 10,
            'enable_command_block' => false,
            'allow_flight' => false,
        ],
        'paper_performance' => [
            'label' => 'Paper Performance',
            'description' => 'Paper defaults with moderate distances and safer public-server settings.',
            'software' => 'paper',
            'motd' => 'A Paper Performance Server',
            'max_players' => 50,
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'online_mode' => true,
            'whitelist' => false,
            'pvp' => true,
            'allow_nether' => true,
            'spawn_protection' => 16,
            'view_distance' => 8,
            'simulation_distance' => 6,
            'enable_command_block' => false,
            'allow_flight' => false,
        ],
        'purpur_crossplay' => [
            'label' => 'Purpur Crossplay',
            'description' => 'Purpur Java server preset prepared for optional Geyser/Floodgate setup.',
            'software' => 'purpur',
            'motd' => 'A Java + Bedrock Crossplay Server',
            'max_players' => 40,
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'online_mode' => true,
            'whitelist' => false,
            'pvp' => true,
            'allow_nether' => true,
            'spawn_protection' => 16,
            'view_distance' => 8,
            'simulation_distance' => 6,
            'enable_command_block' => false,
            'allow_flight' => true,
            'crossplay_enabled' => true,
        ],
        'fabric_technical' => [
            'label' => 'Fabric Technical',
            'description' => 'Fabric-oriented defaults for technical or modded survival communities.',
            'software' => 'fabric',
            'motd' => 'A Fabric Technical Server',
            'max_players' => 20,
            'gamemode' => 'survival',
            'difficulty' => 'hard',
            'online_mode' => true,
            'whitelist' => true,
            'pvp' => false,
            'allow_nether' => true,
            'spawn_protection' => 0,
            'view_distance' => 10,
            'simulation_distance' => 8,
            'enable_command_block' => false,
            'allow_flight' => true,
        ],
        'forge_modded' => [
            'label' => 'Forge Modded',
            'description' => 'Forge defaults for private modded servers.',
            'software' => 'forge',
            'motd' => 'A Forge Modded Server',
            'max_players' => 20,
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'online_mode' => true,
            'whitelist' => true,
            'pvp' => false,
            'allow_nether' => true,
            'spawn_protection' => 0,
            'view_distance' => 8,
            'simulation_distance' => 6,
            'enable_command_block' => false,
            'allow_flight' => true,
        ],
        'bedrock_survival' => [
            'label' => 'Bedrock Survival',
            'description' => 'Bedrock Dedicated Server survival defaults.',
            'software' => 'bedrock',
            'motd' => 'A Bedrock Survival Server',
            'max_players' => 20,
            'gamemode' => 'survival',
            'difficulty' => 'normal',
            'online_mode' => true,
            'whitelist' => false,
            'pvp' => true,
            'allow_nether' => true,
            'spawn_protection' => 16,
            'view_distance' => 10,
            'simulation_distance' => 10,
            'enable_command_block' => false,
            'allow_flight' => false,
        ],
    ],
    'package_profiles' => [
        'paper_basics' => [
            'label' => 'Paper Basics',
            'description' => 'Common Paper/Purpur/Folia plugin baseline.',
            'software' => ['paper', 'purpur', 'folia'],
            'packages' => [
                'modrinth:luckperms',
                'modrinth:viaversion',
                'modrinth:viabackwards',
            ],
        ],
        'paper_voice' => [
            'label' => 'Paper Voice Chat',
            'description' => 'Simple Voice Chat for plugin-based Java servers.',
            'software' => ['paper', 'purpur', 'folia'],
            'packages' => [
                'modrinth:simple-voice-chat',
            ],
        ],
        'fabric_performance' => [
            'label' => 'Fabric Performance',
            'description' => 'Popular server-side Fabric performance baseline.',
            'software' => ['fabric'],
            'packages' => [
                'modrinth:fabric-api',
                'modrinth:lithium',
                'modrinth:ferrite-core',
            ],
        ],
        'modded_voice' => [
            'label' => 'Modded Voice Chat',
            'description' => 'Simple Voice Chat for Fabric, Forge, or NeoForge servers.',
            'software' => ['fabric', 'forge', 'neoforge'],
            'packages' => [
                'modrinth:simple-voice-chat',
            ],
        ],
    ],
    'fallback_versions' => [
        '1.21.11',
        '1.21.10',
        '1.21.8',
        '1.21.7',
        '1.21.6',
        '1.21.5',
        '1.21.4',
        '1.20.6',
        '1.20.4',
    ],
];
